### ISSUE TITLE
When I try to acces stories 

### ISSUE THREAD

**Issue by AlexandruMares** [botfront/botfront#721] opened 2020-08-20 18:42 UTC
**Describe the bug**
Here is the report:

```
Version: 0.25.9
Path: /project/bf/stories
Trace: TypeError: Failed to fetch
    in TypeError: Failed to fetch
    in Unknown
    in Suspense
    in c
    in Unknown
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in W
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in U
```

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MatthieuJnon** [comment] 2020-08-20 18:49
Are you using the botfront project with botfront up and have you made any modifications to the architecture?

**Comment by MatthieuJnon** [comment] 2020-08-20 18:51
This is a duplicate of this issue https://github.com/botfront/botfront/issues/673

**Closed by MatthieuJnon** 2020-08-20 18:51 UTC

**Comment by AlexandruMares** [comment] 2020-08-20 20:28
no modification, I just folowed all the stepts in the documentation for vm...using ubuntu in digital oacean
