### ISSUE TITLE
home page  error

### ISSUE THREAD

**Issue by Kevin-Rose** [botfront/botfront#789] opened 2020-10-21 15:59 UTC
**Describe the bug**
Here is the report:

```
Version: 0.27.0
Path: /project/bf/dialogue
Trace: TypeError: Failed to fetch
    in TypeError: Failed to fetch
    in Unknown
    in Suspense
    in d
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in B
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in $
```

**To Reproduce**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MatthieuJnon** [comment] 2020-10-21 16:41
https://github.com/botfront/botfront/issues/673 this seems to be a duplicate of this issue, please search though other issues before posting

**Closed** 2021-01-15 19:28 UTC
Labels: duplicate
