### ISSUE TITLE
Unable to launch frontend

### ISSUE THREAD

**Issue by NagRamachandran** [botfront/botfront#762] opened 2020-09-29 13:25 UTC
**Describe the bug**
Version: 0.26.0
Path: /project/bf/stories
Trace: TypeError: Failed to fetch
    in TypeError: Failed to fetch
    in Unknown
    in Suspense
    in c
    in Unknown
    in div
    in Unknown
    in div
    in t
    in div
    in t
    in div
    in div
    in W
    in ForwardRef
    in ForwardRef
    in Connect(Component)
    in c
    in Unknown
    in RouterContext
    in Router
    in o
    in c
    in t
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in U

**To Reproduce**
1. npm install -g botfront
2. botfront up
3. Launch browser http://localhost:8888
4. After the user registration, getting above message. and can't proceed further.

botfront logs

botfront-actions | 2020-09-29 13:09:02 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
botfront-actions | 2020-09-29 13:09:02 INFO     rasa_sdk.executor  - Registered function for 'action_my_action'.
botfront-actions | 2020-09-29 13:09:02 DEBUG    rasa_sdk.utils  - Using the default number of Sanic workers (1).
botfront-api    |
botfront-api    | > botfront-api@0.26.0 start /app
botfront-api    | > node app.js
botfront-api    |
botfront-api    | 2020-09-29T13:09:05.703Z [info]: Botfront api 0.26.0 started
botfront-api    | Server running at http://127.0.0.1:8080
botfront-app    | Connecting to MongoDB...
botfront-app    | (node:6) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
botfront-app    | Starting app...
botfront-app    | Note: you are using a pure-JavaScript implementation of bcrypt.
botfront-app    | While this implementation will work correctly, it is known to be
botfront-app    | approximately three times slower than the native implementation.
botfront-app    | In order to use the native implementation instead, run
botfront-app    |
botfront-app    |   meteor npm install --save bcrypt
botfront-app    |
botfront-app    | in the root directory of your application.
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Migrating from version 0 -> 10","time":{"$date":1601384948562},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 1","time":{"$date":1601384948563},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 2","time":{"$date":1601384948564},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 3","time":{"$date":1601384948586},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 4","time":{"$date":1601384948589},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 5","time":{"$date":1601384948591},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 6","time":{"$date":1601384948594},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 7","time":{"$date":1601384948595},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 8","time":{"$date":1601384948597},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 9","time":{"$date":1601384948606},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Running up() on version 10","time":{"$date":1601384948609},"level":"info"}
botfront-app    | {"line":"80","file":"migrations_server.js","message":"Migrations: Finished migrating.","time":{"$date":1601384948612},"level":"info"}
botfront-app    | 2020-09-29T13:09:08.674Z [info] : Botfront 0.26.0 started /server/startup.js
botfront-duckling | no port specified, defaulting to port 8000
botfront-duckling | Listening on http://0.0.0.0:8000
botfront-rasa   | 2020-09-29 13:09:06 DEBUG    rasa.utils.botfront  - Trying to fetch config from http://botfront:3000/graphql (retry #1)
botfront-rasa   | 2020-09-29 13:09:06 DEBUG    rasa.utils.botfront  - [Errno 111] Connection refused

**Comment by MatthieuJnon** [comment] 2020-09-29 13:29
The front end should be on http://localhost:3000 not http://localhost:8888

**Comment by NagRamachandran** [comment] 2020-09-29 13:47
I have deployed this in a local linux server. I am accessing the server using chrome from a different desktop. Here is the docker network mapping . Port 8888 is mapped to 3000. 

Please advise.

c9b42b19139c        botfront/botfront:v0.26.0       "/docker/entrypoint.…"   32 minutes ago      Up 32 minutes       0.0.0.0:8888->3000/tcp     botfront-app
049707ec449b        botfront/botfront-api:v0.26.0   "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes       0.0.0.0:8080->8080/tcp     botfront-api
8fe873b6f4db        botfront/duckling:latest        "/bin/sh -c 'exec du…"   32 minutes ago      Up 32 minutes       0.0.0.0:8000->8000/tcp     botfront-duckling
99fe7e2c68a1        integrated_indigo_actions       "./entrypoint.sh sta…"   32 minutes ago      Up 32 minutes       0.0.0.0:5055->5055/tcp     botfront-actions
f8e0e401f4d1        integrated_indigo_rasa          "rasa run --enable-a…"   32 minutes ago      Up 32 minutes       0.0.0.0:5005->5005/tcp     botfront-rasa
34493e7d24c1        mongo:latest                    "docker-entrypoint.s…"   32 minutes ago      Up 32 minutes       0.0.0.0:27017->27017/tcp   botfront-mongo

**Comment by MatthieuJnon** [comment] 2020-09-29 13:54
Ok then this is a duplicate of https://github.com/botfront/botfront/issues/673 please read through that pr

**Closed by MatthieuJnon** 2020-09-29 13:54 UTC
