### ISSUE TITLE
only previously categorised entities are picked up

### ISSUE THREAD

**Issue by simonjcarr** [botfront/botfront#550] opened 2020-04-08 12:45 UTC
only previously categorized entities are picked up.

I have trained the bot with the following

- search books for html
- search books for php
- search books for javascript tutorials

I have assigned html, php and javascript tutorials to a new entity called "book_search_term"

I would expect that the placement of the search query would have been learned.

However, if I now type 

- search books for html div

"html div" is not seen as a "book_search_term" entity

**Comment by znat** [comment] 2020-04-08 13:48
See the reply to your question in Spectrum here: https://spectrum.chat/botfront/help/only-previously-categorised-entities-are-picked-up~dcd5cdda-6513-4d7f-9e63-09dd23c8bcee

Closing for now as it's probably not a bug but a usage question.

**Closed by znat** 2020-04-08 13:48 UTC
