### ISSUE TITLE
[Error: ENOENT: no such file or directory, access 'C:\C:\Users\SnP\AppData\Roaming\npm\node_modules\botfront\project-template'] {

### ISSUE THREAD

**Issue by akasha1618** [botfront/botfront#118] opened 2019-07-16 11:33 UTC
Hello! I can't get rid of this error,I tried everything, what is the problem?

? What do you want to do? Create a new project
? The project will be created in a subdirectory. How do you want to name it? mid_emerald
[Error: ENOENT: no such file or directory, access 'C:\C:\Users\SnP\AppData\Roaming\npm\node_modules\botfront\project-template'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'access',
  path: 'C:\\C:\\Users\\SnP\\AppData\\Roaming\\npm\\node_modules\\botfront\\project-template'
}
Error: ENOENT: no such file or directory, open 'C:\WINDOWS\system32\mid_emerald\.botfront\docker-compose.yml'
    at Object.openSync (fs.js:447:3)
    at Proxy.readFileSync (fs.js:349:35)
    at getComposeFile (C:\Users\SnP\AppData\Roaming\npm\node_modules\botfront\src\utils.js:154:29)
    at getServices (C:\Users\SnP\AppData\Roaming\npm\node_modules\botfront\src\utils.js:158:22)
    at getMissingImgs (C:\Users\SnP\AppData\Roaming\npm\node_modules\botfront\src\utils.js:168:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async createProject (C:\Users\SnP\AppData\Roaming\npm\node_modules\botfront\src\commands\init.js:151:32)
    at async Object.initCommand [as cmd] (C:\Users\SnP\AppData\Roaming\npm\node_modules\botfront\src\commands\init.js:52:20) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\WINDOWS\\system32\\mid_emerald\\.botfront\\docker-compose.yml'

**Comment by znat** [comment] 2019-07-16 12:31
Duplicate of #115

**Closed by znat** 2019-07-16 12:31 UTC
Labels: duplicate
