### ISSUE TITLE
Impossible to remove an intent from a NLU utterance

### ISSUE THREAD

**Issue by midemarc** [botfront/botfront#178] opened 2019-08-20 21:12 UTC
**Describe the bug**
Trying to remove an intent from an utterance raises an error and does not work.

**To Reproduce**
0. Import NLU examples (see screenshot 1)
1. Add an intent to a NLU utterance
2. Click on the intent and select the empty one, at the top of the list
3. See error "Error: undefined: Intent is required (training_data.common_examples.$.intent) in nlu_models update"

**Expected behavior**
It should be possible to remove an intent from an utterance, not only by selecting the "" (empty) intent, but there should also be a button to do so, like for entities.

**Screenshots**
Import dialog:
<img width="748" alt="rm_intent_impossible_import_data" src="https://user-images.githubusercontent.com/7513460/63378297-eef73a80-c35f-11e9-8c9e-cb9540aaed06.PNG">

Error message :
<img width="999" alt="rm_intent_impossible" src="https://user-images.githubusercontent.com/7513460/63378132-8ad47680-c35f-11e9-9d45-131fa7a8b8fd.PNG">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version:  76.0.3809.100

**Comment by znat** [comment] 2019-08-20 21:24
Hi @midemarc , thanks for submitting this.
Can you elaborate on why removing an intent instead of just setting a new one would be useful?

**Comment by midemarc** [comment] 2019-08-21 01:58
Hi @znat, thanks for your quick answer.
I am currently not annotating the utterances that are out of the scope of my bot. Would you recommend create an out-of-scope intent instead ?

**Comment by znat** [comment] 2019-08-21 22:02
Training data should indeed be trainable. I'm closing the issue as it's not a bug.
Note that in the Activity tab, incoming data can not have intents. So you could keep them there

**Closed by znat** 2019-08-21 22:02 UTC
